# This script plots kdeg in hypoxic conditions for M0M0H and M1M1H experiments

library(tidyverse)
library(ggplot2)
library(ggrepel)
library(bakR)
library(dplyr)
library(readr)

# Read in kdeg files generated by BakR and reshape

M1_kdeg <- read_csv('PATH/TO/BAKR/OUTPUT/Kdegs_M0M1.csv') %>% 
      select(XF, quart, kdeg.x, kdeg.y) %>% 
      pivot_longer(cols = 3:4, names_to = 'Exp_ID', values_to= 'kdeg') %>% 
      mutate(quart_cat = as.factor(quart))

M0H_kdeg <- read_csv('PATH/TO/BAKR/OUTPUT/Kdegs_24hr.csv') %>% 
      select(XF, quart, kdeg.x, kdeg.y) %>% 
      pivot_longer(cols = 3:4, names_to = 'Exp_ID', values_to= 'kdeg')  %>% 
      mutate(quart_cat = as.factor(quart))

M1H_kdeg <- read_csv('PATH/TO/BAKR/OUTPUT/Kdegs_M1M1H.csv') %>% 
      select(XF, quart, kdeg.x, kdeg.y) %>% 
      pivot_longer(cols = 3:4, names_to = 'Exp_ID', values_to= 'kdeg')  %>% 
      mutate(quart_cat = as.factor(quart))

# Plot kdegs according to decile for M0 to M1 

color <- c('#B3A394', '#F87060')

boxesM1 <- ggplot(data=M1_kdeg) +
      scale_fill_manual(values = color) +
      geom_violin(aes(x = quart_cat,
              y=kdeg,
              fill = Exp_ID),
              trim = TRUE, draw_quantiles = 0.5, position = position_dodge(.5), scale = 'width', alpha = 0.5, linewidth = 0.3) +
      scale_y_continuous(trans='log10') +
      
      theme_classic() +
      theme(legend.position="none",
            axis.title = element_blank(),
            axis.text = element_blank(),
            axis.ticks.y = element_line(lineend = 'round', linewidth = 0.5, color = 'black'),
            axis.ticks.x = element_blank(),
            axis.line = element_line(lineend = 'round', linewidth = 0.5))

print(boxesM1)

# Plot kdegs according to decile for M0 to M0H

color <- c('#B3A394', '#306BAC')

boxesM0H <- ggplot(data=M0H_kdeg) +
      scale_fill_manual(values = color) +
      geom_violin(aes(x = quart_cat,
                      y=kdeg,
                      fill = Exp_ID),
                  trim = TRUE, draw_quantiles = 0.5, position = position_dodge(.5), scale = 'width', alpha = 0.5, linewidth = 0.3) +
      scale_y_continuous(trans='log10') +
      
      theme_classic() +
      theme(legend.position="none",
            axis.title = element_blank(),
            axis.text = element_blank(),
            axis.ticks.y = element_line(lineend = 'round', linewidth = 0.5, color = 'black'),
            axis.ticks.x = element_blank(),
            axis.line = element_line(lineend = 'round', linewidth = 0.5))

print(boxesM0H)

# Plot kdegs according to decile for M1 to M1H

color <- c('#F87060', '#CA7DF9')

boxesM1H <- ggplot(data=M1H_kdeg) +
      scale_fill_manual(values = color) +

      geom_violin(aes(x = quart_cat,
                      y=kdeg,
                      fill = Exp_ID),
                  trim = TRUE, draw_quantiles = 0.5, position = position_dodge(.5), scale = 'width', alpha = 0.5, linewidth = 0.3) +
      
      scale_y_continuous(trans='log10') +
      
      theme_classic() +
      theme(legend.position="none",
            axis.title = element_blank(),
            axis.text = element_blank(),
            axis.ticks.y = element_line(lineend = 'round', linewidth = 0.5, color = 'black'),
            axis.ticks.x = element_blank(),
            axis.line = element_line(lineend = 'round', linewidth = 0.5))

print(boxesM1H)

#Save the plot output
out_dir <- 'PATH/FOR/OUTPUT'

ggsave(file.path(out_dir, 'decileBoxes_M1.png'), plot = boxesM1,
       scale = 2, units = 'mm', width = 50, height = 40, dpi = 1000)

ggsave(file.path(out_dir, 'decileBoxes_M0H.png'), plot = boxesM0H,
       scale = 2, units = 'mm', width = 50, height = 40, dpi = 1000)

ggsave(file.path(out_dir, 'decileBoxes_M1H.png'), plot = boxesM1H,
       scale = 2, units = 'mm', width = 50, height = 40, dpi = 1000)


      